group: edge
dist: trusty
language: java
jdk: oraclejdk8
install: true
before_install:
  - sudo rm -rf $HOME/.m2 $HOME/.gradle .gradle gradle build
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk selfupdate
  - touch "$HOME/.sdkman/etc/config"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - sdk use java 8u131-zulu
  - sdk use gradle
  - mkdir -p "$HOME/.sdkman/etc"
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
script:
  - gradle -Penv=github soaptest
  - gradle --stop
before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
